name: Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEB_API_NAME: purple-hrms
  AZURE_WEB_API_PACKAGE_PATH: './publish'
  AZURE_WEB_APP_NAME: purple-hrms-web
  AZURE_WEB_APP_LOCAL_DIRECTORY: './Web/VueApp'
  AZURE_WEB_APP_PACKAGE_PATH: './Web/VueApp/dist'

jobs:
  publish-back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Web/Web.csproj

      - name: Build
        run: dotnet build ./Web/Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Web/Web.csproj --configuration Release --no-build --output '${{ env.AZURE_WEB_API_PACKAGE_PATH }}'

      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_API_NAME }}
          publish-profile: '${{ secrets.AZURE_WEB_API_PUBLISH_PROFILE }}'
          package: ${{ env.AZURE_WEB_API_PACKAGE_PATH }}

  publish-front-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}

      - name: Build Vue App
        run: npm run build:prod
        working-directory: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}

      - name: Deploy to Azure App Service
          run: |
            # Install Azure CLI
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            
            # Login using deployment credentials
            AZURE_APP_NAME="purple-hrms-web"
            AZURE_RESOURCE_GROUP="rg-purple-env"
            DEPLOYMENT_TOKEN="bda33d49acacafcb2c5d24abb6d481d29c0ac14a5fe3899169c5842f19221b7004-f5831375-23e4-435a-a557-d35d5dc4c9a2000190802c470b00"
            
            echo bda33d49acacafcb2c5d24abb6d481d29c0ac14a5fe3899169c5842f19221b7004-f5831375-23e4-435a-a557-d35d5dc4c9a2000190802c470b00 | az webapp deployment source config-zip --resource-group rg-purple-env --name purple-hrms-web --src dist.zip
            
          working-directory: ./Web/VueApp/dist  # Ensure this is correct based on your project structure
