name: Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEB_API_NAME: purple-hrms
  AZURE_WEB_API_PACKAGE_PATH: './publish'
  AZURE_WEB_APP_NAME: purple-hrms-web
  AZURE_WEB_APP_LOCAL_DIRECTORY: './Web/VueApp'
  AZURE_WEB_APP_PACKAGE_PATH: './Web/VueApp/dist'

jobs:
  publish-back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Web/Web.csproj

      - name: Build
        run: dotnet build ./Web/Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Web/Web.csproj --configuration Release --no-build --output '${{ env.AZURE_WEB_API_PACKAGE_PATH }}'

      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_API_NAME }}
          publish-profile: '${{ secrets.AZURE_WEB_API_PUBLISH_PROFILE }}'
          package: ${{ env.AZURE_WEB_API_PACKAGE_PATH }}

  publish-front-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}

      - name: Build Vue App
        run: npm run build:prod
        working-directory: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEB_APP_PACKAGE_PATH }}
