name: Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEB_API_NAME: purple-api
  AZURE_WEB_API_PACKAGE_PATH: './publish'
  AZURE_WEB_APP_NAME: purple
  AZURE_WEB_APP_LOCAL_DIRECTORY: './Web/VueApp'
  AZURE_WEB_APP_PACKAGE_PATH: 'dist'

jobs:
  publish-back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Web/Web.csproj

      - name: Run Unit Tests
        run: dotnet test ./UnitTests/UnitTests.csproj --configuration Release"

      - name: Build
        run: dotnet build ./Web/Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Web/Web.csproj --configuration Release --no-build --output '${{ env.AZURE_WEB_API_PACKAGE_PATH }}'

      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_API_NAME }}
          publish-profile: '${{ secrets.AZURE_WEB_API_PUBLISH_PROFILE }}'
          package: ${{ env.AZURE_WEB_API_PACKAGE_PATH }}

  publish-front-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}

      - name: Build Vue App
        run: npm run build:prod
        working-directory: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}

      - name: Deploy to Azure App Service
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_WEB_APP_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ env.AZURE_WEB_APP_LOCAL_DIRECTORY }}
          api_location: ''
          output_location: ${{ env.AZURE_WEB_APP_PACKAGE_PATH }}

  close-pull-request-job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_WEB_APP_DEPLOY_TOKEN }}
          action: 'close'
