name: Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: purple-hrms
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Web/Web.csproj

      - name: Build
        run: dotnet build ./Web/Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Web/Web.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deploy
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
