name: Staging Deployment
run-name: 'Staging Deployment #${{ github.run_number }}'

on:
  push:
    branches: [staging]

concurrency:
  group: staging-deployment
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/template-build.yaml
    with:
      ENVIRONMENT: staging
      DOTNET_VERSION: '9.0.x'
    secrets: inherit

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/template-deploy.yaml
    with:
      ENVIRONMENT: staging
      AZURE_WEB_APP_NAME: motomerkado-api-staging
    secrets: inherit
