name: Template - Deploy Pipeline

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
      AZURE_WEB_APP_NAME:
        type: string
        required: true
    secrets:
      AZURE_WEB_API_PUBLISH_PROFILE:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Artifact - Download application
        uses: actions/download-artifact@v5
        with:
          name: publish-${{ inputs.ENVIRONMENT }}
          path: publish

      - name: Azure - Deploy Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_API_PUBLISH_PROFILE }}
          package: publish
